### ISSUE TITLE
mode-line and header line are too large

### ISSUE THREAD

**Issue by thinkiny** [ryuslash/yoshi-theme#5]
Emacs version: 28
<img width="866" alt="Screen Shot 2021-08-30 at 1 27 45 AM" src="https://user-images.githubusercontent.com/5935030/131259612-fb783d90-0d37-4646-8365-9968967a3a42.png">
<img width="810" alt="Screen Shot 2021-08-30 at 1 27 49 AM" src="https://user-images.githubusercontent.com/5935030/131259615-84c9a5cf-3212-4c32-a76e-b7e071d2b2c4.png">

**Comment by ryuslash** [comment]
Hey!

Thanks for reporting this. As far as I can tell from the screenshots it looks like the mode line and header line look the way I intended to. I've added a border around both to make it look like they're padded.

```
`(mode-line ((t (:background ,yoshi-2 :foreground ,yoshi-6 :box (:color ,yoshi-2 :line-width 5 :style nil)))))
`(mode-line-buffer-id ((t (:background ,fgred :foreground ,yoshi-6 :box (:color ,fgred :line-width 5 :style nil)))))
```

**Comment by thinkiny** [comment]
ok，thanks for explain
